// <auto-generated />
using System;
using AlgoLab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoLab.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922143613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoLab.Domain.Entities.Algorithm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("algorithms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "const-function",
                            Name = "Const Function"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Code = "sum-function",
                            Name = "Sum Function"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Code = "product-function",
                            Name = "Product Function"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Code = "naive-polynomial",
                            Name = "Naive Polynomial"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Code = "horner-polynomial",
                            Name = "Horner Polynomial"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Code = "bubble-sort",
                            Name = "Bubble Sort"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Code = "quick-sort",
                            Name = "Quick Sort"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Code = "tim-sort",
                            Name = "Tim Sort"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Code = "multiply-matrix",
                            Name = "Matrix Multiplication"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111a"),
                            Code = "smooth-sort",
                            Name = "Smooth Sort"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111b"),
                            Code = "sieve-of-eratosthenes",
                            Name = "Sieve of Eratosthenes"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111c"),
                            Code = "simple-pow",
                            Name = "Simple Pow"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111d"),
                            Code = "recursive-pow",
                            Name = "Recursive Pow"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111e"),
                            Code = "quick-recursive-pow",
                            Name = "Quick Recursive Pow"
                        });
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.BenchmarkRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("double precision");

                    b.Property<int>("N")
                        .HasColumnType("integer");

                    b.Property<long?>("StepsCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId", "N")
                        .IsUnique();

                    b.ToTable("benchmark_runs", (string)null);
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.BenchmarkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndM")
                        .HasColumnType("integer");

                    b.Property<int>("EndN")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ForceRecalculate")
                        .HasColumnType("boolean");

                    b.Property<int?>("StartM")
                        .HasColumnType("integer");

                    b.Property<int>("StartN")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.ToTable("BenchmarkSessions");
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.SessionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uuid");

                    b.Property<double?>("ExecutionTimeMs")
                        .HasColumnType("double precision");

                    b.Property<bool>("FromCache")
                        .HasColumnType("boolean");

                    b.Property<int>("N")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<long?>("StepsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkRunId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionRuns");
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.BenchmarkRun", b =>
                {
                    b.HasOne("AlgoLab.Domain.Entities.Algorithm", "Algorithm")
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.BenchmarkSession", b =>
                {
                    b.HasOne("AlgoLab.Domain.Entities.Algorithm", "Algorithm")
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.SessionRun", b =>
                {
                    b.HasOne("AlgoLab.Domain.Entities.BenchmarkRun", "BenchmarkRun")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoLab.Domain.Entities.BenchmarkSession", "Session")
                        .WithMany("Runs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkRun");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AlgoLab.Domain.Entities.BenchmarkSession", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
